//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "font_versions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_versions_unique")]
    pub font_id: i64,
    #[sea_orm(unique_key = "idx_versions_unique")]
    pub version_number: i64,
    pub file_path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub changelog: Option<String>,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fonts::Entity",
        from = "Column::FontId",
        to = "super::fonts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Fonts,
}

impl Related<super::fonts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fonts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
