//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fonts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub version_number: i64,
    pub file_path: String,
    pub uploaded_by: Option<i64>,
    pub status: String,
    pub download_count: i64,
    pub favorite_count: i64,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comments::Entity")]
    Comments,
    #[sea_orm(has_many = "super::font_tags::Entity")]
    FontTags,
    #[sea_orm(has_many = "super::font_versions::Entity")]
    FontVersions,
    #[sea_orm(has_many = "super::user_favorites::Entity")]
    UserFavorites,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UploadedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::font_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FontTags.def()
    }
}

impl Related<super::font_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FontVersions.def()
    }
}

impl Related<super::user_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFavorites.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::font_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::font_tags::Relation::Fonts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
