//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::access_tokens::Entity as AccessTokens;
pub use super::comments::Entity as Comments;
pub use super::font_tags::Entity as FontTags;
pub use super::font_versions::Entity as FontVersions;
pub use super::fonts::Entity as Fonts;
pub use super::tags::Entity as Tags;
pub use super::user_favorites::Entity as UserFavorites;
pub use super::users::Entity as Users;
