//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::font_tags::Entity")]
    FontTags,
}

impl Related<super::font_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FontTags.def()
    }
}

impl Related<super::fonts::Entity> for Entity {
    fn to() -> RelationDef {
        super::font_tags::Relation::Fonts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::font_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
